<a href="https://colab.research.google.com/github/Datastudy3769/Deeplearning/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print("TensorFlow:", tf.__version__)

TensorFlow: 2.13.0


## 텐서 와 연산

In [ ]:
#스칼라 텐서를 생성
t1 = tf.constant(42)
print(t1)
#배열을 가지고 생성
t2 = tf.constant([[1, 2, 3], [4, 5, 6]])
print(t2)

tf.Tensor(42, shape=(), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
#인덱싱
print(t2[:, 1:]) #행전체 그리고 열은 1번 부터 끝까지 선택
print(t2[:, 1]) #첫번째 열만 선택 - 일차원 배열로 생성
print(t2[:, 1, tf.newaxis]) #첫번째 열만 선택 - 다차원 배열로 생성
#tf.newaxis를 추가하면 차원이 하나 추가됩니다.

tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)
tf.Tensor([2 5], shape=(2,), dtype=int32)
tf.Tensor(
[[2]
 [5]], shape=(2, 1), dtype=int32)


In [ ]:
#연산
print(t2 + 10) #broadcast 연산 수행
print(tf.square(t2))
print(t2 @ tf.transpose(t2))

tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 1  4  9]
 [16 25 36]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[14 32]
 [32 77]], shape=(2, 2), dtype=int32)


In [ ]:
from tensorflow import keras
K = keras.backend
K.square(K.transpose(t2)) + 10




<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 26],
       [14, 35],
       [19, 46]], dtype=int32)>

In [ ]:
import numpy as np
ar = np.array([2, 3, 4])
print(np.sum(ar))

#numpy 배열을 가지고 Tensor 생성
x = tf.constant(ar)
print(x)
#Tensor를 numpy 배열로 변경
print(type(x.numpy()))


#numpy 와 Tensor 연산에 데이터 공유 가능
print(tf.square(ar))
print(np.square(x))







9
tf.Tensor([2 3 4], shape=(3,), dtype=int64)
<class 'numpy.ndarray'>
tf.Tensor([ 4  9 16], shape=(3,), dtype=int64)
[ 4  9 16]


In [ ]:
# 자료형이 달라서 에러 발생
try:
    tf.constant(10) + tf.constant(10.3)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2] name: 


In [ ]:
try:
    print(tf.cast(tf.constant(10), tf.float32) + tf.constant(10.3))
except tf.errors.InvalidArgumentError as ex:
    print(ex)

tf.Tensor(20.3, shape=(), dtype=float32)


In [ ]:
#변수 생성
v = tf.Variable([[1, 2, 3], [4, 5, 6]])
print(v)
v.assign(5 + v)
print(v)
v[0,0].assign(42)
print(v)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 6,  7,  8],
       [ 9, 10, 11]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[42,  7,  8],
       [ 9, 10, 11]], dtype=int32)>


## 문자열 Tensor

In [ ]:
tf.constant("안녕하세요") #하나의 기본 자료형으로 인코딩 해서 저장


<tf.Tensor: shape=(), dtype=string, numpy=b'\xec\x95\x88\xeb\x85\x95\xed\x95\x98\xec\x84\xb8\xec\x9a\x94'>

In [ ]:
#Tensor 배열 - 실수 3개를 저장하는 텐서 배열을 생성
array = tf.TensorArray(dtype=tf.float32, size=3)
#3개의 데이터 저장
array = array.write(0, tf.constant([1.0, 2.0]))
array = array.write(1, tf.constant([3.0, 4.0]))
array = array.write(2, tf.constant([5.0, 6.0]))
#첫번째 데이터 읽기
print(array.read(1))

tf.Tensor([3. 4.], shape=(2,), dtype=float32)
tf.Tensor(
[[1. 2.]
 [0. 0.]
 [5. 6.]], shape=(3, 2), dtype=float32)


In [ ]:
#ragged tensor: 각 배열의 길이가 달라도 됩니다.
ar = tf.ragged.constant([[10, 20], [30, 40, 50], [50, 60]])
print(ar)

<tf.RaggedTensor [[10.0, 20.0], [30.0, 40.0, 50.0], [50.0, 60.0]]>


In [ ]:
#희소 텐서 생성
#3행 4열의 행렬을 만들고 indices 자리에 values의 값을 순서대로 배정한
#희소 행렬
s = tf.SparseTensor(indices=[[0,1], [1, 0], [2, 3]],
                             values = [1.0, 2.0, 3.0],
                    dense_shape=[3, 4])
print(tf.sparse.to_dense(s))

tf.Tensor(
[[0. 1. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 3.]], shape=(3, 4), dtype=float32)


In [ ]:
s1 = tf.constant([[1, 2, 3, 1, 1], [2, 4, 5, 8, 11]])
s2 = tf.constant([[1, 2, 3, 4, 4], [2, 7, 5, 8, 9]])
print(s1)
print(s2)
print(tf.sparse.to_dense(tf.sets.union(s1, s2)))

tf.Tensor(
[[ 1  2  3  1  1]
 [ 2  4  5  8 11]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[1 2 3 4 4]
 [2 7 5 8 9]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  0  0  0]
 [ 2  4  5  7  8  9 11]], shape=(2, 7), dtype=int32)


In [ ]:
#노드 생성
node1 = tf.constant(3.0)
node2 = tf.constant(4.0)

#그래프 실행
print(node1)
print(node2)



tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)


In [ ]:
#텐서플로우 코드 최적화가 가능하도록 작성
@tf.function
def tf_cube(x):
  print(x)#값의 변화가 없는 구문이므로 함수 호출전에 전부 수행해버림
  return x ** 3 #텐서플로우 함수 호출 구문으로 변경되서 실행

result = tf_cube(tf.constant(2.0))
print(result)

Tensor("x:0", shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)


In [ ]:
#2행 5열의 난수 발생: 0에서 1사이에서 균등한 분포로
result = tf.random.uniform([2, 5], 0.0, 1.0)
print(result)

tf.Tensor(
[[0.4301132  0.7273488  0.6812712  0.3207115  0.05291784]
 [0.24522781 0.1313839  0.04546034 0.65579915 0.4084462 ]], shape=(2, 5), dtype=float32)


In [ ]:
#2행 5열의 난수 발생: 0에서 1사이에서 정규 분포에서 평균은 0
#표준 편차는 1
result = tf.random.normal([2, 5], 0.0, 1.0)
print(result)

tf.Tensor(
[[ 0.19888227 -1.963883   -0.823702   -0.18127418  0.14239594]
 [-0.9020395   0.59392685  2.1631913  -0.2401765  -0.51862496]], shape=(2, 5), dtype=float32)


## 뉴런 생성

In [ ]:
# 활성화 함수 - 시그모이드
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))




In [ ]:
#입력 값
X = 1.0
#타겟
y = 0.0
#가중치를 랜덤하게 설정
w = tf.random.normal([1], 0, 1)
#출력
output = sigmoid(X * w)
print("예측값:", output)

예측값: 0.5667301379008409


In [ ]:
#경사 하강법
for i in range(1000):
  output = sigmoid(X * w)
  error = y - output
  w = w + X * 0.1 * error #학습률을 0.1로 설정
  if i % 50 == 0:
    print(i, output, error)

0 9.907749788319505e-05 -9.907749788319505e-05
50 9.883215852561443e-05 -9.883215852561443e-05
100 9.858742662650783e-05 -9.858742662650783e-05
150 9.834330068210877e-05 -9.834330068210877e-05
200 9.810221142013493e-05 -9.810221142013493e-05
250 9.786395281554538e-05 -9.786395281554538e-05
300 9.762627280770029e-05 -9.762627280770029e-05
350 9.73891699917862e-05 -9.73891699917862e-05
400 9.715264296639923e-05 -9.715264296639923e-05
450 9.691669033353669e-05 -9.691669033353669e-05
500 9.668131069858885e-05 -9.668131069858885e-05
550 9.644650267033085e-05 -9.644650267033085e-05
600 9.621437504982556e-05 -9.621437504982556e-05
650 9.598527733656467e-05 -9.598527733656467e-05
700 9.575672507959185e-05 -9.575672507959185e-05
750 9.552871698048456e-05 -9.552871698048456e-05
800 9.530125174390986e-05 -9.530125174390986e-05
850 9.507432807761717e-05 -9.507432807761717e-05
900 9.484794469243079e-05 -9.484794469243079e-05
950 9.462210030224268e-05 -9.462210030224268e-05


In [ ]:
#경사 하강법 문제 발생
#가중치 만을 곱하게 되는 경우 Input이 0이면 가중치가 변경되지 않음
X = 0
y = 1
w = tf.random.normal([1], 0, 1)
for i in range(1000):
  output = sigmoid(X * w)
  error = y - output
  w = w + X * 0.1 * error #학습률을 0.1로 설정
  if i % 50 == 0:
    print(i, output, error)

0 0.5 0.5
50 0.5 0.5
100 0.5 0.5
150 0.5 0.5
200 0.5 0.5
250 0.5 0.5
300 0.5 0.5
350 0.5 0.5
400 0.5 0.5
450 0.5 0.5
500 0.5 0.5
550 0.5 0.5
600 0.5 0.5
650 0.5 0.5
700 0.5 0.5
750 0.5 0.5
800 0.5 0.5
850 0.5 0.5
900 0.5 0.5
950 0.5 0.5


In [ ]:
#경사 하강법 문제 발생 - 편향을 추가해서 해결
X = 0
y = 1
w = tf.random.normal([1], 0, 1)

b = tf.random.normal([1], 0, 1)
for i in range(1000):
  output = sigmoid(X * w + 1 * b)
  error = y - output
  w = w + X * 0.1 * error #학습률을 0.1로 설정
  b = b + 1 * 0.1 * error
  if i % 50 == 0:
    print(i, output, error)

0 0.19769055719411938 0.8023094428058806
50 0.7405050458806913 0.2594949541193087
100 0.8749037773548664 0.12509622264513365
150 0.9201117781390925 0.0798882218609075
200 0.9418358007999427 0.05816419920005733
250 0.9544366851244958 0.045563314875504246
300 0.9626181063519526 0.03738189364804745
350 0.968341525052936 0.031658474947063975
400 0.9725627616916909 0.02743723830830913
450 0.9758011007238457 0.024198899276154262
500 0.9783621276398727 0.021637872360127264
550 0.9804371786102818 0.01956282138971821
600 0.9821519302602834 0.017848069739716643
650 0.9835923354875891 0.016407664512410935
700 0.9848190589327792 0.015180941067220788
750 0.9858761985197096 0.014123801480290354
800 0.986796489112087 0.01320351088791305
850 0.987604820445823 0.012395179554177016
900 0.988320367829414 0.011679632170585985
950 0.9889582222256703 0.011041777774329686


In [ ]:
#AND를 뉴런으로 구현
import numpy as np

X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [0], [0], [1]])
b = tf.random.normal([1], 0, 1)
#입력이 2개라서 가중치를 2개 생성
w = tf.random.normal([2], 0, 1)

for i in range(2000):
  #오차의 합계를 저장할 변수
  error_sum = 0
  #모든 입력을 대입해서 수행
  for j in range(4):
    output = sigmoid(np.sum(X[j] * w) + 1 * b)
    error = y[j][0] - output
    w = w + X[j] * 0.1 * error
    b = b + 1 * 0.1 * error
    error_sum += error
  if i % 100 == 0:
    print(i, error_sum)





0 -1.1665479772138694
100 -0.16681177071598186
200 -0.10904554401338185
300 -0.08161033857188016
400 -0.06523055162065017
500 -0.054277463751154054
600 -0.04642819395161185
700 -0.04053027593148256
800 -0.03593800750487211
900 -0.03226510582526504
1000 -0.029261807207844742
1100 -0.02676223539972042
1200 -0.02464905314717715
1300 -0.02284172265430076
1400 -0.021277147018298928
1500 -0.01991037920129546
1600 -0.018707036437792035
1700 -0.017639257761379867
1800 -0.016683874640690308
1900 -0.0158271048037832


In [ ]:
#predict
for i in range(4):
  print("X:", X[i], "Y:", y[i], "Predict:", sigmoid(np.sum(X[i]*w)+b))





X: [0 0] Y: [0] Predict: 2.3859212940203562e-05
X: [0 1] Y: [0] Predict: 0.025055601760881764
X: [1 0] Y: [0] Predict: 0.025132126868913727
X: [1 1] Y: [1] Predict: 0.9652389536262862


### OR를 경사하강법으로 구현

In [ ]:
#OR를 뉴런으로 구현
import numpy as np

X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [1]])
b = tf.random.normal([1], 0, 1)
#입력이 2개라서 가중치를 2개 생성
w = tf.random.normal([2], 0, 1)

for i in range(2000):
  #오차의 합계를 저장할 변수
  error_sum = 0
  #모든 입력을 대입해서 수행
  for j in range(4):
    output = sigmoid(np.sum(X[j] * w) + 1 * b)
    error = y[j][0] - output
    w = w + X[j] * 0.1 * error
    b = b + 1 * 0.1 * error
    error_sum += error
  if i % 100 == 0:
    print(i, error_sum)

#predict
for i in range(4):
  print("X:", X[i], "Y:", y[i], "Predict:", sigmoid(np.sum(X[i]*w)+b))

0 2.8366574756811316
100 -0.08025280284898889
200 -0.04597845927129632
300 -0.03210872374276885
400 -0.024675307328566057
500 -0.020016786656115795
600 -0.016820888909497497
700 -0.014493686595122665
800 -0.012724405683308897
900 -0.011335344487683294
1000 -0.010216040593091905
1100 -0.009295588567631394
1200 -0.008525604837557953
1300 -0.00787173159984228
1400 -0.007310634009254385
1500 -0.006823192003146031
1600 -0.006395806485227563
1700 -0.006018789982041986
1800 -0.005683556375782703
1900 -0.005382366060515363
X: [0 0] Y: [0] Predict: 0.025358698113860104
X: [0 1] Y: [1] Predict: 0.9899271020454483
X: [1 0] Y: [1] Predict: 0.9898691388541552
X: [1 1] Y: [1] Predict: 0.9999972904275755


In [ ]:
#XOR를 뉴런으로 구현
import numpy as np

X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [0]])
b = tf.random.normal([1], 0, 1)
#입력이 2개라서 가중치를 2개 생성
w = tf.random.normal([2], 0, 1)

for i in range(2000):
  #오차의 합계를 저장할 변수
  error_sum = 0
  #모든 입력을 대입해서 수행
  for j in range(4):
    output = sigmoid(np.sum(X[j] * w) + 1 * b)
    error = y[j][0] - output
    w = w + X[j] * 0.1 * error
    b = b + 1 * 0.1 * error
    error_sum += error
  if i % 100 == 0:
    print(i, error_sum)

#predict
for i in range(4):
  print("X:", X[i], "Y:", y[i], "Predict:", sigmoid(np.sum(X[i]*w)+b))

0 0.3488599804736595
100 -0.03161134029103496
200 -0.0064011109085940765
300 -0.001290925357368966
400 -0.0002602852431067282
500 -5.247948279474279e-05
600 -1.0584020262993654e-05
700 -2.137841300209331e-06
800 -4.3184965781151163e-07
900 -8.004110507719986e-08
1000 -6.980329025907395e-08
1100 -6.980329025907395e-08
1200 -6.980329025907395e-08
1300 -6.980329025907395e-08
1400 -6.980329025907395e-08
1500 -6.980329025907395e-08
1600 -6.980329025907395e-08
1700 -6.980329025907395e-08
1800 -6.980329025907395e-08
1900 -6.980329025907395e-08
X: [0 0] Y: [0] Predict: 0.5128177040587629
X: [0 1] Y: [1] Predict: 0.5000000363215804
X: [1 0] Y: [1] Predict: 0.48718236853665897
X: [1 1] Y: [0] Predict: 0.4743815336379531


In [ ]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [0]])

model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=2, activation='sigmoid',
                          input_shape=(2,)),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])

model.compile(optimizer=tf.keras.optimizers.SGD(lr=0.01), loss='mse')

model.summary()

history = model.fit(X, y, epochs=20000, batch_size=1)

model.predict(X)






Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 2)                 6         
                                                                 
 dense_5 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/20000
4/4 [==============================] - 1s 5ms/step - loss: 0.2619
Epoch 2/20000
4/4 [==============================] - 0s 6ms/step - loss: 0.2617
Epoch 3/20000
4/4 [==============================] - 0s 7ms/step - loss: 0.2614
Epoch 4/20000
4/4 [==============================] - 0s 9ms/step - loss: 0.2612
Epoch 5/20000
4/4 [==============================] - 0s 5ms/step - loss: 0.2610
Epoch 6/20000
4/4 

In [ ]:
#가중치 와 편향 확인
for weight in model.weights:
  print(weight)



